language: node_js
node_js:
    - "0.10"
before_install:
    - "npm install -g grunt"
    - "npm install -g bower"
    - "npm install -g jshint"
install:
    - "bower install"
    - "npm install"
script:
    - "grunt release"
notifications:
    email: false