apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ember-graph
  description: A data persistence library for Ember.js with a focus on complex object graphs
  annotations:
    github.com/project-slug: stingerlabs/ember-graph
    sonarqube.org/project-key: stingerlabs_ember-graph
    snyk.io/org-id: de43b40c-8694-45ec-985c-404d8ab5977e
  links:
    - url: https://greenlightguru.slack.com/archives/C05FS321Y6R
      title: '#ask channel'
      icon: help
  tags:
    - javascript
    - ember
spec:
  type: library
  lifecycle: production
